### ISSUE TITLE
Training GenRe with my own dataset - how to generate it

### ISSUE THREAD

**Issue by vicentepedro** [xiumingzhang/GenRe-ShapeHD#1]
Hi Xiuming!

Thanks for sharing the code.
I would like to train GenRe on my own dataset.

I already have:
1. the RGB image
2. the silhouette image
3. the normals
4. the aligned 3D model (voxel representation)

I need, at least, the spherical maps as well, right?

How can I create my own dataset to train GenRe? Do you have any example on how you created yours on chairs, aeroplanes and cars based on shapenet?

Thanks in advance, 
Best,
Pedro

**Comment by xiumingzhang** [comment]
Hi Pedro,

Yes, you'd need to generate spherical maps from depth maps. For this purpose, you should use this class: https://github.com/xiumingzhang/GenRe-ShapeHD/blob/master/toolbox/spherical_proj.py#L31.

For creating your own dataset (and getting a sense of what data you need to train GenRe), we recommend taking a look at the released data that we used to train GenRe (please see https://github.com/xiumingzhang/GenRe-ShapeHD#data).
