### ISSUE TITLE
What are the parameters for rendering the data?

### ISSUE THREAD

**Issue by rozentill** [xiumingzhang/GenRe-ShapeHD#11]
Hi there,

Thank you for releasing the codes. I wonder if you can provide or where I can find the parameters you used for the rendering, e.g. the camera position, whether orthographic or perspective, the range of depth(normalization using min/max or a specified range) and etc. 

Thanks,
Ryan

**Comment by xiumingzhang** [comment]
Hi Ryan,

To answer your questions: we randomized the azimuth and elevation angles of the camera, but fixed its  distance from the object (which lies at the world origin) at 2.2. We used perspective projection. We normalized depth values using min/max (so for GenRe, we also saved these min/max values).

Here's one of the .xml files we used for Mitsuba rendering. Hope it's helpful.

```
<?xml version="1.0" encoding="utf-8"?>

<scene version="0.5.0">
    <shape type="shapenet">
        <string name="filename" value="/path/to/ShapeNetCore.v2/02691156/1b300fd9ad4050e6301fa0a0663ee996/models/model_normalized.obj"/>
        <float name="maxSmoothAngle" value="60"/>
    </shape>

    <emitter type="envmap" id="env">
        <string name="filename" value="/path/to/pano_agopyyqqoosawv.jpg"/><float name="scale" value="1.5"/><boolean name="cache" value="false"/>
    </emitter>

    <integrator type="multichannel">
        <integrator type="path"/>
        <integrator type="field">
            <string name="field" value="shNormal"/>
            <vector name="origin" x="-2.17377455880512005903" y=".33763929383474039631" z="-.02653063795658653414"/>
        </integrator>
        <integrator type="field">
            <string name="field" value="distance"/>
            <float name="dist" value="1"/>
        </integrator>
    </integrator>

    <sensor type="perspective">
        <transform name="toWorld">
            <lookAt target="0,0,0" origin="-2.17377455880512005903, .33763929383474039631, -.02653063795658653414" up="0,1,0"/>
        </transform>

        <sampler type="halton">
            <integer name="sampleCount" value="64"/>
        </sampler>

        <film type="hdrfilm">
            <integer name="width" value="480"/>
            <integer name="height" value="480"/>
            <string name="pixelFormat" value="rgb, rgb, rgb"/>
            <string name="channelNames" value="color, normal, depth"/>
            <boolean name="banner" value="false"/>
        </film>
    </sensor>
</scene>
```

**Comment by rozentill** [comment]
Thanks Xiuming, I have one more question. I observed the predicted final voxels are all in the same orientation even the inputs are from different views, is there any rotation/scaling matrix I can use to rotate/scale them to match the pose in the input image?

**Comment by xiumingzhang** [comment]
Right. If you trained your networks using canonical-pose supervision, then your predicted voxels are always in the same, canonical pose. This is the case for ShapeHD.

In the case of GenRe, we trained our networks in different poses that align with the input views (this is good for projections, and subsequently generalization), and the network predictions are view-aligned with the input views.

If you download our training dataset, you will find `<class_id>_<object_id>_view???_gt_rotvox_samescale_128.npz` in each object folder. The voxels there have been aligned with their respective input views. Training your networks with these as supervision will give you view-aligned predictions (what we did in GenRe).

**Comment by rozentill** [comment]
Hi, I have a follow-up question, you mentioned you use random azimuth and elevation angles. But did you use the same field of view(FOV) or it's also random? Thanks.

**Comment by xiumingzhang** [comment]
No, FoV (or equivalently, the focal length) was fixed. As seen from the .xml pasted above, we didn't specify the focal length, so Mitsuba's default focal length was used.

**Comment by xiumingzhang** [comment]
@rozentill 
We have released all XML files used for rendering the dataset some time ago. Just FYI in case you find them useful. You can find a description in the README file and the download link [here](http://genre.csail.mit.edu/downloads/training_xml.zip).
