### ISSUE TITLE
How to generate full spherical maps / rotated vox for GenRe in current view?

### ISSUE THREAD

**Issue by JiahuiLei** [xiumingzhang/GenRe-ShapeHD#12]
Hi!

Thanks for sharing the code and dataset.

Could you please provide some information about how to generate full spherical map as ground truth for training? Or I notice that there are rotated voxels in dataset dir for each spherical map and how to generate such aligned voxel?

I met some problem when I tried to align the shapenet object and depth when I rendered my own dataset with some specific poses.

Thanks!

**Comment by 4ri4Slr** [comment]
Hi there,

I am having the same problem. Could you please explain how the view-aligned voxels are generated?

Thanks
