### ISSUE TITLE
GenRe:How to calculate CD from voxel

### ISSUE THREAD

**Issue by zhouxuting** [xiumingzhang/GenRe-ShapeHD#13]
Hi,there,
Thank you for releasing this repo. I wanna use CD metric for evaluation. It is said in the paper that we need to sample the point from the isosurfaces of the voxel pair(pred and gt) , and then calculate the CD of the sampled points. 
I don't know the detail of this process, I would appreciate it if you provide some code for this.
Thank you. 

Best regards,
Xuting

**Comment by ztzhang** [comment]
Hi,

Thank you for your interest in our paper!

We use the testing pipeline provided by our [Pix3D](https://github.com/xingyuansun/pix3d) project. You can refer to functions [here](https://github.com/xingyuansun/pix3d/blob/749d8fa95f991279039a090445b77403af1258bc/eval/eval.py#L57) as a starting point.

**Comment by zhouxuting** [comment]
Thank you for your quick reply. I tried Pix3D project and it works well.  I have some doubt about how to set the parameters of eval.py. I used voxels stored as numpy file(.npy) create from [here](https://github.com/xiumingzhang/GenRe-ShapeHD/blob/0e322273aebe1c97e27c79be55f7988f0b2bb955/models/genre_full_model.py#L186) as  input. I don't know how to set the following parameters:
1.list1_max_value, list2_max_value
2.no_resample1,no_resample2
Could you give me some guidance or advice?
Thank you a lot.

Best regards,
Xuting
