### ISSUE TITLE
How to use multi-GPU

### ISSUE THREAD

**Issue by zhouxuting** [xiumingzhang/GenRe-ShapeHD#14]
Hi, there.
Thank you for sharing. I tried to use multi-GPU to run this, but failed. I found there is a function named data_parallel_decorator in model/netinterface.py and tried to write self.net=data_parallel_decorator(self.net) for multi-GPU, but there is a bug about the input structure. Is there any demo or guidance about how to use multi-GPU?
Thank you !

Best regards,
Xuting

**Comment by xiumingzhang** [comment]
Hi Xuting,

We never trained these models on multiple GPUs, so I'm afraid you'd have to figure it out yourself if multi-GPU training is what you really need.
