### ISSUE TITLE
How to speed up training?

### ISSUE THREAD

**Issue by rozentill** [xiumingzhang/GenRe-ShapeHD#17]
Hi,

I am trying to retrain marrnet2+3D-GAN and fine-tune them. But it seems each epoch takes ~1500s, if train 200epch, it would take ~100h only for Marrnet2. It seems 3D-GAN would take much longer time. Did I miss something or is there any method to speed up the training? Thank you so much.

**Comment by xiumingzhang** [comment]
This really depends on how big your "one epoch" is, and what GPU you are on. How many seconds does Marrnet2 take to train on a batch of 4 points, for example?

**Comment by rozentill** [comment]
Hi, thanks for your reply. I just tried a default setting, so the batch size is 4 and it tooks ~1500 seconds for one epoch. The GPU I am using is GTX 1080 with 11GB video memory. Is it possible to finish the training in one day?

**Comment by xiumingzhang** [comment]
I traced back to our training checkpoints: with similar hardware, the Marrnet2 results are already looking pretty reasonable after 6 hours, so I'd say it's possible to finish the training in a day.
