### ISSUE TITLE
MarrNet2 training stops at Eval 3/1000

### ISSUE THREAD

**Issue by rozentill** [xiumingzhang/GenRe-ShapeHD#18]
Hi,

I am training MarrNet2 using default setting on shapenet chair dataset. It seems it always stops at Eval 3/1000 as shown below:
![Capture](https://user-images.githubusercontent.com/11246898/59730376-00ed1d80-91f7-11e9-912a-2c7123d86617.PNG)

Any idea what's going on?

Thanks!

**Comment by ztzhang** [comment]
hi,
This might be an issue with Pytorch dataloader dead locking. Please see https://github.com/pytorch/pytorch/issues/1355.
One possible fix is to turn off the multiprocessing/multithreading for numpy and opencv. This works for most of our cases.

**Comment by rozentill** [comment]
Works now, thanks!
