### ISSUE TITLE
training for wgangp model

### ISSUE THREAD

**Issue by congyang12345** [xiumingzhang/GenRe-ShapeHD#20]
it is difficult for training the wgangp model, could you provide your trained wgangp model? thank you!

**Comment by xiumingzhang** [comment]
Have you tried training a WGANGP model with our training pipeline, parameters, and our released data?

Here's the training script:
https://github.com/xiumingzhang/GenRe-ShapeHD/blob/master/scripts/train_wgangp.sh

If everything you are using is from this release, it should work out-of-the-box.

**Comment by congyang12345** [comment]
I have tried training the WGANGP model with your pipeline, parameters and your released data for a month. But it took long time for training. As I calculated, it will take several months for training with 1000 epochs. I urgently need this trained model for a research work , so could you provide your trained wgangp model? thank you!

**Comment by ztzhang** [comment]
@congyang12345 If you urgently need a category-specific WGANGP generator, you can check out models trained on chairs and cars [here](https://github.com/junyanz/VON)
