### ISSUE TITLE
how to get the depth_minmax.npy for our own dataset?

### ISSUE THREAD

**Issue by qiminchen** [xiumingzhang/GenRe-ShapeHD#21]
We are training the marrnet1 with our own dataset but found out that we are missing the depth_minmax, could you please tell how to generate the depth_minmax? Thanks in advance!

**Comment by xiumingzhang** [comment]
While generating your own dataset, you will render the depth. The depth should be rendered as raw, absolute values, possibly stored in .exr. The depth maps people show are usually offset, scaled, and discretized from these raw maps. Once you have the raw maps, the `min` in `depth_minmax` is just the minimum value, and the `max` is the maximum excluding the background depth.

**Comment by qiminchen** [comment]
Hi, we render the `depth` images and `depth_minmax` using Blender but it seems like we got `depth_minmax` wrong because the marrnet1 did not converge, the normal/depth/silhou loss kept increasing after some epochs and `depth_minmax loss` is extremely large. If we set `--pred_depth_minmax` to false, the results looked pretty decent. Is it possible that you open the render `depth` code?

**Comment by xiumingzhang** [comment]
Hi, could you clarify what you mean by "got the `depth_minmax` wrong"? I might have missed something, but if those values are wrong, then you should fix the rendering code until they are correct before training the models.
