### ISSUE TITLE
Range of mesh sizes

### ISSUE THREAD

**Issue by krebin** [xiumingzhang/GenRe-ShapeHD#22]
Hello, I am attempting to train marrnet on another dataset, but the depth I obtain from my dataset is very large and varies a lot in comparison to the shapenet dataset. Are the sizes of the meshes in the shapenet dataset constrained to a certain range?

**Comment by xiumingzhang** [comment]
Hi, you should normalize them according to a single rule. For instance, one possible rule could be that the bounding box of each model should fit into the same unit ball.
