### ISSUE TITLE
spherical inpainting network predict same spherical maps

### ISSUE THREAD

**Issue by qiminchen** [xiumingzhang/GenRe-ShapeHD#27]
Hi,

We are training the spherical inpainting network and found out that the network predicts the same `spherical_full` and `spherical_partial` for all objects, below is the result from 22 epoch:

`spherical_full`:
![image](https://user-images.githubusercontent.com/45860234/61925515-8adc8480-af21-11e9-87f8-a44701fa5967.png)

`spherical_partial` is totally white:
![image](https://user-images.githubusercontent.com/45860234/61925532-9334bf80-af21-11e9-870e-c7e9a1040db3.png)

The arguments we are using:
```
--load_offline False
--joint_train False
```

Any ideas why this happens? Thanks in advance!

**Comment by qiminchen** [comment]
https://github.com/xiumingzhang/GenRe-ShapeHD/blob/62fc39b6a4b7c90d3df39b2949f1b0f7a9b3fcb3/models/depth_pred_with_sph_inpaint.py#L119-L124
I plotted the `pred_abs_depth` from line119 and it looked ok, but when I plotted the `proj`, it was incorrect, `proj` of all objects look the same, and `proj.min()` and `proj.max()` are also the same

**Comment by xiumingzhang** [comment]
Has this been resolved by setting the center correctly, as in the other issue?

**Comment by qiminchen** [comment]
We solved this issue by changing the camera distance to an appropriate number. thanks!
