### ISSUE TITLE
normals definition

### ISSUE THREAD

**Issue by HeidiCheng** [xiumingzhang/GenRe-ShapeHD#28]
I have printed the values of normals' ground truth, and got the results that they are in the range of 0-100. May I ask about how to get the value? Is it scale from RGB or something else? Thank you!

**Comment by xiumingzhang** [comment]
Could you clarify which normal file(s) are you referring to?

**Comment by HeidiCheng** [comment]
Hi, we are using the 2.5D normal map in marrnet2.py and taking it from
batch['normal']. May I also ask about how to obtain the 2.5D normal map
from Shapenet object, we are not sure about the axis definition for the
normal map. Thank you!
Sincerely,
Heidi

**Comment by xiumingzhang** [comment]
Closing. Feel free to reopen with followup questions.

**Comment by HeidiCheng** [comment]
Thanks for your reply!
Sincerely,
Heidi
