### ISSUE TITLE
Training wgangp always generate same gen_voxel.obj

### ISSUE THREAD

**Issue by qiminchen** [xiumingzhang/GenRe-ShapeHD#29]
Hi, I'm training the wgangp on our dataset but it generates the same result as following for all valid_voxel in every epoch, we also ran the code on shapenet and it generated the same result as our. is this correct? any idea why this happens? thanks! We only have one view per object, so I am assuming that each view is the canonical view.

![image](https://user-images.githubusercontent.com/45860234/62329413-a9370880-b46a-11e9-8a9f-94e464c71b13.png)

this is our loss at epoch 19

![image](https://user-images.githubusercontent.com/45860234/62329681-6fb2cd00-b46b-11e9-8aa0-66a2d76a0354.png)

**Comment by qiminchen** [comment]
Any thoughts about this or any direction to look at? Thank you!

**Comment by xiumingzhang** [comment]
Sorry for the delayed response. Can you try if
https://github.com/xiumingzhang/GenRe-ShapeHD/issues/25
solves this problem?

**Comment by qiminchen** [comment]
I tried different iso-surfaces threshold but none of them worked, even I tried training the wgangp using ShapeNet, it still visualized the triangle, any suggestions? Thanks in advance.

**Comment by xiumingzhang** [comment]
Glad that visualization issue has been solved.

It makes sense to add `sigmoid` or `tanh` to the last layer. I think adding either would work too.
