### ISSUE TITLE
Can this be run on Windows currently?

### ISSUE THREAD

**Issue by rozentill** [xiumingzhang/GenRe-ShapeHD#3]
Hi there,

Thanks for releasing the codes. I was trying to run it on Windows, but met some issues. So I wonder what changes need to be made for running on Windows, such as compiling cam_bp using CUDA myself and if there are some things cannot be done in Windows.

Thank you in advance.

**Comment by ztzhang** [comment]
Sorry we currently do not support windows. My guess is that compiling pytorch extensions might be different on windows.
