### ISSUE TITLE
The GenRe's output is not even close when testing with full_model.pt 

### ISSUE THREAD

**Issue by samhu1989** [xiumingzhang/GenRe-ShapeHD#30]
hi,
I am runing the test_genre with your latest code and released model, following the instructions in README
The result is not even close, not even with the few test cases in the repo
I think I may did something wrong somewhere, but I have no clue where is it.
In my results, the predicted depth seems correct, but the sphere map and final reconstuction are really bad.
my results are shown as follows: 
(seems the output pred_proj_depth do not have the same upside with  pred_voxel, but pred_proj_depth all looks correct, however the pred_proj_sph_full and pred_voxel are not even close)
![01](https://user-images.githubusercontent.com/1378449/62717763-116f8680-ba37-11e9-8d9b-b1c36bfb70d4.PNG)
![02](https://user-images.githubusercontent.com/1378449/62717779-192f2b00-ba37-11e9-90ce-d4b57f621f7d.PNG)
![03](https://user-images.githubusercontent.com/1378449/62717785-1c2a1b80-ba37-11e9-96d8-a6439a1dd013.PNG)
![04](https://user-images.githubusercontent.com/1378449/62717796-1fbda280-ba37-11e9-89d8-43534edc2127.PNG)

**Comment by ztzhang** [comment]
Hi，
This really is wierd. I'm trying to see if I can reproduce this. Just to
confirm, are you using the same environment in the repo?

It seems the sphere prediction is off. Usually it preserve the depth
prediction. I'll try to see if I can reproduce; thanks for letting us know!

**Comment by samhu1989** [comment]
my environment is not exactly same， it is not conda-based， my pip freeze output is uploaded as requirements.txt
My pip freeze 
[requirements.txt](https://github.com/xiumingzhang/GenRe-ShapeHD/files/3484740/requirements.txt)

**Comment by samhu1989** [comment]
In order to use scipy.misc.imresize from scipy 1.3.0. I also adapt your util_camera.py and download piutil.py from old scipy repo. However, I don't think this is the cause, since it somehow only affect the inpanting part
[util_camera.py.txt](https://github.com/xiumingzhang/GenRe-ShapeHD/files/3484755/util_camera.py.txt)
[piutil.py.txt](https://github.com/xiumingzhang/GenRe-ShapeHD/files/3484756/piutil.py.txt)

**Comment by samhu1989** [comment]
Hi, I think I have found the issue, the pyembree is not properly installed in my environment and your code catch the except and return some default value in util_sph.py which is why i couldn't locate the issue. I will let you know if it is fixed after I install pyembree properly.

**Comment by samhu1989** [comment]
the issue is fixed after I properly re-installed the pyembree
I recommend to at least print some warning in the util_sph.render_model when catch the exception

**Comment by ztzhang** [comment]
@samhu1989 great to hear that! I'll add a warning to it. Thanks!

**Comment by vincentgc** [comment]
> the issue is fixed after I properly re-installed the pyembree
> I recommend to at least print some warning in the util_sph.render_model when catch the exception

Hi, can you tell me how the pyembree is installed? by pip or conda?

**Comment by samhu1989** [comment]
conda  from conda-forge

**Comment by vincentgc** [comment]
> conda from conda-forge

OK, Thanks! I will try it.
