### ISSUE TITLE
Is the released pretrained ShapeHD model only for chairs?

### ISSUE THREAD

**Issue by ZezhouCheng** [xiumingzhang/GenRe-ShapeHD#32]
Hi Xiuming,

I'd like to test the ShapeHD model on airplanes? Is the pre-trained model on airplanes available?

Thanks!

**Comment by xiumingzhang** [comment]
Hi, our ShapeHD model is trained on three classes combined: airplanes, chairs, and cars, so it should work on airplanes out of the box.
