### ISSUE TITLE
nvcc not found

### ISSUE THREAD

**Issue by dannygelman1** [xiumingzhang/GenRe-ShapeHD#34]
Hello, 
I am trying to run GenRe-ShapeHD in a conda environment with CUDA 9.2 on Ubuntu 18.04.2 LTS and am getting stuck when I run `sudo ./build_toolbox.sh`
The error I am getting is "cuda available but nvcc not found. Please add nvcc to $PATH"
I tried to fix this by adding a file to the GenRe-ShapeHD directory that adds `/usr/local/cuda-9.2/bin` to the path.

After doing this and running nvcc -V, it looks like it was able to find nvcc becasue it returns 
`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2018 NVIDIA Corporation`
`Built on Tue_Jun_12_23:07:04_CDT_2018`
`Cuda compilation tools, release 9.2, V9.2.148`

But it still is giving me the same error that it cannot find nvcc when I run `sudo ./build_toolbox.sh`
Do you know what could be causing this issue?

Thank you

**Comment by ztzhang** [comment]
Hi, are you still having the same issue? I think the build do not need sudo privileges tho.

**Comment by dannygelman1** [comment]
I got past this problem! I had to add the line `conda activate shaperecon` inside each of the three setup.sh files. And it worked with both `sudo ./build_toolbox.sh` and `./build_toolbox.sh`
