### ISSUE TITLE
perspective in reconstruction results from MarrNet

### ISSUE THREAD

**Issue by qiminchen** [xiumingzhang/GenRe-ShapeHD#36]
Hi, I'm reproducing the MarrNet training on the chair class, the reconstruction results are good but it somehow gives me kind of perspective surfaces as follow, the surfaces get transparent when rotating the object in different views. Do you know how to solve this? Is it because of the `voxel_isosurf_th`? `voxel_isosurf_th =0.25` is used.

![image](https://user-images.githubusercontent.com/45860234/66626091-c9422100-ebab-11e9-9dab-fb39709dcd93.png)
![image](https://user-images.githubusercontent.com/45860234/66626102-d9f29700-ebab-11e9-9015-57acc23047c3.png)
![image](https://user-images.githubusercontent.com/45860234/66626244-5c7b5680-ebac-11e9-9194-65e75cb18a3b.png)

**Comment by xiumingzhang** [comment]
The easiest thing to try is to sweep that `voxel_isosurf_th` threshold. I guess a lower threshold should give you a "watertight" visualization.

**Comment by ztzhang** [comment]
I think this is because your visualizing software is not rendering the
back-faced normals.
