### ISSUE TITLE
IoU in MarrNet paper

### ISSUE THREAD

**Issue by qiminchen** [xiumingzhang/GenRe-ShapeHD#37]
Hi, I noticed that the IoU number under "4.1 3D Reconstruction on ShapeNet" section in MarrNet paper is 0.57, what class is this IoU for? Or is it the average IoU over the chair, plane and car classes? The best IoU I can get with MarrNet on the chair class is around 0.45, is this IoU reasonable since Reprojection consistency loss is not needed in synthetic data?

By the way, the IoU in ShapeHD paper on chair class is 0.488 which is lower than MarrNet, shouldn't it be higher since ShapeHD generates better reconstructions? Or maybe it is supposed to be lower because of the naturalness loss? Or we cannot just simply compare MarrNet and ShapeHD?

Thanks

**Comment by ztzhang** [comment]
@jiajunwu might know more about the marrnet setup.
For ShapeHD, we compared it against our network without GAN Loss, which is nearly identical to Marrnet. We used different renderings and viewpoints than the ones used by Marrnet, therefore directly comparing scores might not be accurate. If you are looking for a comparison with Marrnet, you can refer to the model without the GAN Loss.

**Comment by jiajunwu** [comment]
Hi @qiminchen , the IoU is on chairs only.  Regarding the comparison, I agree with Zhoutong's comments.
