### ISSUE TITLE
The results of GenRe testing seem not right

### ISSUE THREAD

**Issue by zaoqiweixaio** [xiumingzhang/GenRe-ShapeHD#4]
Hi, Xiuming

Thank you very much for sharing your excellent work.
When I run scripts/test_genre.sh with your trained models, I couldn't get the results as you show.
Here are the results that I get for the 4 testing examples:
![result](https://user-images.githubusercontent.com/8140574/51019267-4ad13800-15b5-11e9-8a96-6dcbc9e0acda.png)
ShapeHD testing goes well.
Could you please help me? Are the models uploaded wrong or anything else?

Thanks a lot!

Dan

**Comment by ztzhang** [comment]
Hi, this seems to be a problem with trimesh installation. I can reproduce this problem with some installation of trimesh. I'm trying to fix this problem by uploading a trimesh installation script; please stay tuned.
