### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by fxy2012** [xiumingzhang/GenRe-ShapeHD#40]
Hello, Xiuming. I ran codes following your steps, while when I ran `./build_toolbox.sh` to build the environment, errors occurred as follows. Could you please help me solve this problem?
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fxy/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

```
Thanks a lot!

**Comment by xiumingzhang** [comment]
This is usually due to your `PYTHONPATH` being messed up: very likely it contains paths to two `numpy` libraries.

**Comment by yuyingyeh** [comment]
Hi, in [this](https://stackoverflow.com/questions/17386880/does-anaconda-create-a-separate-pythonpath-variable-for-each-new-environment) post it said that Anaconda doesn't use `PYTHONPATH`. I also encountered same problem.
