### ISSUE TITLE
Where to find test dataset for shapehd?

### ISSUE THREAD

**Issue by fxy2012** [xiumingzhang/GenRe-ShapeHD#42]
```
rgb_pattern='./downloads/data/test/shapehd/*_rgb.*'
mask_pattern='./downloads/data/test/shapehd/*_mask.*'
```
I have downloaded the dataset `http://genre.csail.mit.edu/downloads/shapenet_cars_chairs_planes_20views.tar`, but I can't find where the test folder is.  The dataset unzipped as follows,
![1](https://user-images.githubusercontent.com/49487269/69399285-85a11200-0d28-11ea-8e45-e3d49c0c796f.png)
Is this normal?

**Comment by ztzhang** [comment]
hi, [here](http://genre.csail.mit.edu/downloads/test_drc_release.txt) is the test items we used on these classes. I believe the released data is both train+test, and the txt file contains the test items' id only.
That being said, we highly recommend using Pix3D for testing purposes.
