### ISSUE TITLE
How to set gan patameter in fineturn_shapehd.sh ?

### ISSUE THREAD

**Issue by fxy2012** [xiumingzhang/GenRe-ShapeHD#44]
python train.py \
    --net shapehd \
    --marrnet2 "$marrnet2" \
    --gan "$gan" \
    --dataset shapenet \
    --classes "$class" \
    --canon_sup \
    --w_gan_loss 1e-3 \
    --batch_size 4 \
    --epoch_batches 200 \
    --eval_batches 10 \
    --optim adam \
    --lr 1e-3 \
    --epoch 1000 \
    --vis_batches_vali 10 \
    --gpu "$gpu" \
    --save_net 1 \
    --workers 4 \
    --logdir "$outdir" \
    --suffix '{classes}_w_ganloss{w_gan_loss}' \
    --tensorboard \
    $*

How to set $gan parameter?

**Comment by xiumingzhang** [comment]
That's the path to the trained GAN:
https://github.com/xiumingzhang/GenRe-ShapeHD/blob/master/scripts/finetune_shapehd.sh#L8
