### ISSUE TITLE
Question about the "**_gt_rotvox_samescale_128.npz" in the training dataset

### ISSUE THREAD

**Issue by vincentgc** [xiumingzhang/GenRe-ShapeHD#46]
Hi, 
I've downloaded the dataset for training the GenRE. In this dataset, the ‘**_gt_rotvox_samescale_128.npz’ contains a 'voxel' file (128*128*128 array). Each point in this array is 0 or 1 or a decimal from 0 to 1. I understand that the 0 and 1 can represent the voxel. But what does the decimal mean?

**Comment by ztzhang** [comment]
This is used by GenRe and we used TSDF instead of binary voxels.

**Comment by vincentgc** [comment]
Why are the values in TSDF in the range of 0 to 1, not -1 to 1?

**Comment by vincentgc** [comment]
Why are the values of this TSDF file in the range of 0 to 1, not -1 to 1? @ztzhang

**Comment by ztzhang** [comment]
Sorry for the confusion, it should be TDF, not TSDf. Since most shapes are not watertight in the dataset, we use TDF instead of TSDF for data preparation.

**Comment by vincentgc** [comment]
Thanks for your quick reply!
Do you have any references about TDF? I am new to 3D reconstruction and I did not find a specific definition of TDF on google.

**Comment by xiumingzhang** [comment]
Check this out: https://link.springer.com/chapter/10.1007%2F978-3-319-11755-3_40
