### ISSUE TITLE
[Minor Issue] Discrepancy between model names

### ISSUE THREAD

**Issue by vicentepedro** [xiumingzhang/GenRe-ShapeHD#5]
https://github.com/xiumingzhang/GenRe-ShapeHD/blob/0f8b5f658b823e0edd99d4d201fe1ce19eec5af3/scripts/test_shapehd.sh#L7

Hi @ztzhang and @xiumingzhang 

There is a small discrepancy (it's a minor issue) on the file name of the trained models (shapehd.pt and marrnet1_with_minmax.pt) and the expected ones on `scripts/test_shapehd.sh`

Best,
Pedro

**Comment by xiumingzhang** [comment]
Thanks Pedro for pointing this out! We've fixed this in commit c624446.
