### ISSUE TITLE
How can I read 2.5D sketch

### ISSUE THREAD

**Issue by jordgey** [xiumingzhang/GenRe-ShapeHD#50]
hi，I have downloaded this，

```
This repo comes with a few Pix3D images and ShapeNet renderings, located in ```
downloads/data/test, for testing purposes.
For training, we make available our RGB and 2.5D sketch renderings, paired with their corresponding 3D shapes, for ShapeNet cars, chairs, and airplanes, with each object captured in 20 random views. Note that this .tar is 143 GB.
wget http://genre.csail.mit.edu/downloads/shapenet_cars_chairs_planes_20views.tar -P downloads/data/
mkdir downloads/data/shapenet/
tar -xvf downloads/data/shapenet_cars_chairs_planes_20views.tar -C downloads/data/shapenet/
```

Is  02691156_1a04e3eab45ca15dd86060f189eb133_view000_spherical.npz the  2.5D sketch ？And how can I read it by python?Use numpy?
Looking forward to your reply!

**Comment by jordgey** [comment]
![Uploading 01.PNG…]()

**Comment by jordgey** [comment]
![Uploading 捕获.PNG…]()

**Comment by ztzhang** [comment]
please see the code in the dataset file [here](https://github.com/xiumingzhang/GenRe-ShapeHD/blob/5ca2a936d41849317ffc0d6e1a37ae6386c7ab48/datasets/shapenet.py#L166)

**Comment by jordgey** [comment]
> please see the code in the dataset file [here](https://github.com/xiumingzhang/GenRe-ShapeHD/blob/5ca2a936d41849317ffc0d6e1a37ae6386c7ab48/datasets/shapenet.py#L166)

Thank you very much! And do   'obj_spherical' and 'spherical_depth' are the data of  2.5D sketch?

**Comment by jordgey** [comment]
Thank you very much! And Are 'obj_spherical' and 'spherical_depth' the data of 2.5D sketch?
