### ISSUE TITLE
How can I generate 2.5D sketch

### ISSUE THREAD

**Issue by jordgey** [xiumingzhang/GenRe-ShapeHD#51]
I download shapenet_cars_chairs_planes_20views.tar,and I want to  generate other category  2.5D sketch  from  the RGB(like 02691156_1a04e3eab45ca15dd86060f189eb133_view000_spherical.npz), is there any download link,or how can I generate them?

**Comment by jordgey** [comment]
Looking forward to your reply!

**Comment by xiumingzhang** [comment]
To generate training data for categories other than the three provided, please see #11.
