### ISSUE TITLE
About 'obj_spherical' and 'depth_spherical'

### ISSUE THREAD

**Issue by Gourd6** [xiumingzhang/GenRe-ShapeHD#52]
Hi, there.
Thank you for sharing.

I want to ask in the shapenet_cars_chairs_planes_20views.tar's 'obj_spherical' and 'depth_spherical' data are the Partial Spherical Map or the Inpainted Spherical Map?

**Comment by Gourd6** [comment]
And another question: I failed to built the cuda extension with` ./build_toolbox.sh  `. What is this  used for? If I do not build it ，Can I run the code successfully on the cpu?

**Comment by xiumingzhang** [comment]
`obj_spherical` refers to full spherical maps (multi-view), whereas `depth_spherical` refers to partial spherical maps (single-view).
