### ISSUE TITLE
Inquiry for the camera parameters corresponding to the rendered dataset

### ISSUE THREAD

**Issue by skyir0n** [xiumingzhang/GenRe-ShapeHD#53]
Hi, there.
Thank you for sharing your codes and datasets.

I am planning to adopt your datasets for object pose estimation using 2.5D dataset and Mitsuba scene files. I found that you have uploaded the Mitsuba scene files at Oct. 20.
You said in the repository that camera poses can be retrieved from these scene files.
However, It is hard to figure out camera parameters corresponding to rendered image data.
To be specific, intrinsic and extrinsic parameters in addition to other camera ones such as focal length, etc., seem hard to be retrieved from the uploaed xml files.

Could you provide the camera parameters used to render dataset?
Or Is it available to let me know how to compute those parameters from the xml files?

**Comment by xiumingzhang** [comment]
Hi, unfortunately, we don't have the bandwidth now to extract the camera parameters from our released scene XMLs. What you need to do is noting down the Mitsuba's default parameters, looking at our XML files to find out which parameters got overridden (so those not overridden used the default parameters), and finally translating those parameters into camera intrinsics and extrinsics. We are happy to help if in the process you want us to clarify anything.

**Comment by alexzhou907** [comment]
Has this been solved? I am also interested in extracting the intrinsic and extrinsic parameters from the XML files.

**Comment by skyir0n** [comment]
> Has this been solved? I am also interested in extracting the intrinsic and extrinsic parameters from the XML files.

Unfortunately, I failed to extract the camera parameters from the XML files. Instead, I adopted the R2N2 dataset and re-rendered RGB images and depth maps with camera parameters.

**Comment by alexzhou907** [comment]
Yes. Please look at https://github.com/xiumingzhang/GenRe-ShapeHD/blob/master/util/util_camera.py to know how to use target, origin, up to convert global coordinates to image coordinates. And https://github.com/xiumingzhang/GenRe-ShapeHD/blob/master/util/util_cam_para.py has utility functions that extract the three parameters given XML file.

**Comment by alexzhou907** [comment]
Additionally if you want extrinsic parameters. Mitsuba's source code https://github.com/mitsuba-renderer/mitsuba2/blob/a02a943cf51a4887fa61f674ba3ecc981057754a/include/mitsuba/core/transform.h has a look_at function which gives you exactly what you want.

**Comment by xiumingzhang** [comment]
@skyir0n 
We have released all XML files used for rendering the dataset some time ago. Just FYI in case you find them useful. You can find a description in the README file and the download link [here](http://genre.csail.mit.edu/downloads/training_xml.zip).
