### ISSUE TITLE
How to obtain surface normal images from the raw depth data?

### ISSUE THREAD

**Issue by caixialiu-bjut** [xiumingzhang/GenRe-ShapeHD#59]
Hi, thank you for sharing your code. 
Could you help sovle the problem: how to obtain surface normal images from the raw depth data? Is surface normal images obtained during the rendering?  
I want to obtain depth images and corresponding normals by blender. Could you tell some details?
Thanks! Look forward your reply.

**Comment by xiumingzhang** [comment]
We rendered normals directly rather than compute them from depth. We used
Mitsuba, but if you want to do this in Blender, take a look at:
https://github.com/xiumingzhang/xiuminglib/blob/master/xiuminglib/blender/render.py#L444
