### ISSUE TITLE
How to render images with high-dynamic-range backgrounds with illumination channels

### ISSUE THREAD

**Issue by hzxie** [xiumingzhang/GenRe-ShapeHD#6]
As mentioned in the ShapeHD paper, ``to boost the realism
of the rendered RGB images, we put three different types of backgrounds behind
the object during rendering. One third of the images are rendered in a clean white
background; **one third are rendered in high-dynamic-range backgrounds with
illumination channels that produce realistic lighting**. We render the remaining one
third images with backgrounds randomly sampled from the SUN database [61].''

I wonder how to render images with high-dynamic-range backgrounds with illumination channels.

**Comment by xiumingzhang** [comment]
Mitsuba is able to use an HDR environment map as the light source, providing a natural illumination. Once you have the HDR maps, you can set them up as the light source in Mitsuba. Please see pg. 133 of https://www.mitsuba-renderer.org/releases/current/documentation.pdf.

**Comment by hzxie** [comment]
So, what environment map do you use?
Can you provide the script for generating this kind of training data?

**Comment by xiumingzhang** [comment]
We crawled those environment maps from the web. Example websites that provide such downloads include https://www.hdri-hub.com/free-hdri-environments-for-download.
