### ISSUE TITLE
I want to use the wgangp which is in the shapehd

### ISSUE THREAD

**Issue by jordgey** [xiumingzhang/GenRe-ShapeHD#60]

**Comment by jordgey** [comment]
Hi,
 I want to use the wgangp  , and my question is that Is the wgangp suitable for point clouds instead of voxels ？

**Comment by xiumingzhang** [comment]
Maybe, although we haven't tried WGAN-GP on point clouds. Consider checking out: https://arxiv.org/pdf/2006.07029.pdf.
