### ISSUE TITLE
how to get the intrinsic and extrinsic parameters when i use the GenRE

### ISSUE THREAD

**Issue by HADESforCode** [xiumingzhang/GenRe-ShapeHD#63]
I want to use the intrinsic and extrinsic camera parameters to reproject the pointcloud back to the image。so i want to know how to get these parameters

**Comment by xiumingzhang** [comment]
See #53 and #11

**Comment by HADESforCode** [comment]
what if i use it to unseen class things，how can i get those unseen classes parameters.

**Comment by HADESforCode** [comment]
![2020-09-01 00-13-49屏幕截图](https://user-images.githubusercontent.com/39392962/91742059-34dc1500-ebe8-11ea-9147-51fd1f16caa7.png)
this is what i got.
![2020-09-01 00-13-36屏幕截图](https://user-images.githubusercontent.com/39392962/91742085-3efe1380-ebe8-11ea-80c6-2bba77196b59.png)
this is what i want.

**Comment by HADESforCode** [comment]
> See #53 and #11

sry, i still not solve the problem.

**Comment by Rabona17** [comment]
> > See #53 and #11
> 
> sry, i still not solve the problem.

Hi, have you solved the problem yet? I think I might have the same issue
