### ISSUE TITLE
how can I make my own data set？

### ISSUE THREAD

**Issue by 963852a** [xiumingzhang/GenRe-ShapeHD#64]
Thank you for making your own working code open source. If I want to train my own data set, how can I make my own data set?

**Comment by xiumingzhang** [comment]
Thanks for the question. To generate your own dataset, you will need to take a look at our Mitsuba scene files to render the images (https://github.com/xiumingzhang/GenRe-ShapeHD#data), and produce the shape supervision with helper functions provided in `toolbox/` and `util/`.

I wish we had documentations for this procedure, but unfortunately we don't. Please feel free to reach out if you encounter any problems in doing this.
