### ISSUE TITLE
Camera parameters used when Creating the Dataset

### ISSUE THREAD

**Issue by vicentepedro** [xiumingzhang/GenRe-ShapeHD#7]
Hi all!

I was trying to generate my own dataset, however the spherical maps I generate for my own dataset (from depth and from the voxel representation) do not match.

I'm using the camera back projection module:

https://github.com/xiumingzhang/GenRe-ShapeHD/blob/0e322273aebe1c97e27c79be55f7988f0b2bb955/toolbox/cam_bp/cam_bp/modules/camera_backprojection_module.py#L12

Which is used here:
https://github.com/xiumingzhang/GenRe-ShapeHD/blob/b68e54d74dcceb5b3ba8b9846c210d10c70a1675/models/genre_full_model.py#L8
and here:
https://github.com/xiumingzhang/GenRe-ShapeHD/blob/b68e54d74dcceb5b3ba8b9846c210d10c70a1675/models/depth_pred_with_sph_inpaint.py#L7

**My question are the following:**

- what is fl? Is it the focal length of your camera? In which units?
- If our camera is not at a distance of 2.2 from the object, is it sufficient to change it here, or we should change somewhere else?

Thanks in advance for your time.

Best,
Pedro

**Comment by ztzhang** [comment]
Sorry for the belated reply.
We now released all xml files used for rendering the dataset, you can find a description in the README file and the download link [here](http://genre.csail.mit.edu/downloads/training_xml.zip)

As for FL, it is actually FL/W where w is the size of the pixel, all in metric space. This value is set to match the ones on the xml file.
