### ISSUE TITLE
Could you provide state_dicts for the discriminator of the pretrained models

### ISSUE THREAD

**Issue by alejandrobarredo** [xiumingzhang/GenRe-ShapeHD#74]
I am working on a research on XAI and I would love to be able to use your Shapehd model. However, I need also the discriminator.
Do you have it stored by any chance?

Thank you in advance,
Alejandro

PS: If you want any further information about the research, just contact me. I will be gratefull to talk about it.

**Comment by xiumingzhang** [comment]
Some digging led me to this:

https://drive.google.com/file/d/170x9CfTzDyWnRonTEJY1Pll17sJ6KgOb/view?usp=sharing

Give it a try, and I hope this is the right checkpoint!

**Comment by alejandrobarredo** [comment]
I really appreciate it.
I'll give it a try right away and let u know.

**Comment by alejandrobarredo** [comment]
I have just tried it.
It works, thank you very much.
I'll send you and update when the paper is published.
