### ISSUE TITLE
how to train marrnet of shapehd?

### ISSUE THREAD

**Issue by Tong-Gao-dream** [xiumingzhang/GenRe-ShapeHD#76]
Hello! What should I write in Items_all.txt, RGB. TXT and other files that I need to run train_marrynet1.sh? I am looking forward to your help in your busy schedule. I want to retrain your model with my own data set.

**Comment by xiumingzhang** [comment]
Hi, each line in that file should be the path prefix. For instance:
```
/your/path/to/shapenet_render_fixdist2.2/04099429/3c43ddee5e1d4723db652c825617e3be/04099429_3c43ddee5e1d4723db652c825617e3be_view000
```
