### ISSUE TITLE
GenRe docker environment for 2080Ti and 1080Ti

### ISSUE THREAD

**Issue by hansongfang** [xiumingzhang/GenRe-ShapeHD#77]
Thanks for sharing the code. I manage to create two docker environment that suppports old GPU card 1080Ti and newer 2080Ti respectively. It does take time to figure out a solution to run GenRe on 2080Ti as the CUDA9.0 is not compatible with 2080Ti. My solution is to upgrade the CUDA9.0 to CUDA9.2. Hope my docker environment will save others time. 

To run with Nvidia2080Ti, use the following docker "shanaf/deeplearning:genre-cuda9.2".  
To run with Nvidia1080Ti, use the following docker "shanaf/deeplearning:genre".

Note to compile libraries in toolbox, I edit the setup.sh. 1) add " export TORCH_CUDA_ARCH_LIST="7.0"" at the top of setup.sh. 2) update the gencode as following 

`cmd="nvcc -c -std=c++11 -o back_projection_kernel.cu.o back_projection_kernel.cu -x cu -Xcompiler -fPIC -I ${TORCH}/lib/include/TH -I ${TORCH}/lib/include -I ${TORCH}/lib/include/THC -I ${HERE} -I ${TORCH}/lib/include\
        -gencode arch=compute_30,code=sm_30 \
        -gencode arch=compute_35,code=sm_35 \
        -gencode arch=compute_52,code=sm_52 \
        -gencode arch=compute_61,code=sm_61 \
        -gencode arch=compute_70,code=sm_70 \
        -gencode arch=compute_70,code=compute_70 "`

**Comment by xiumingzhang** [comment]
Thanks for sharing, Songfang!
