### ISSUE TITLE
dataset link broken? 

### ISSUE THREAD

**Issue by ZENGXH** [xiumingzhang/GenRe-ShapeHD#78]
Hi Xiuming, 

It seems the dataset link http://genre.csail.mit.edu/downloads/training_xml.zip is not working now? Could you help checking with that? 

Thanks!

**Comment by ztzhang** [comment]
It seems to be a browser issue for me.  The link is blocked by my Chrome browser but works fine if you do wget or copy paste it directly in your browser.

**Comment by ZENGXH** [comment]
It works now. Thanks!
